language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then echo extension=functional.so | tee -a /home/vagrant/.phpfarm/inst/php*/lib/php.ini ; fi"
  - php --re functional
  - phpunit

notifications:
  email:
    - lstrojny@php.net
