language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native PHPUNIT="php -n -dextension=.libs/functional.so `which phpunit`"
  - FUNCTIONAL=userland PHPUNIT="phpunit"

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -c "$PHPUNIT"

notifications:
  email:
    - lstrojny@php.net
