language: php

php:
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php:
      - 5.6
      - nightly

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make && make install; echo extension=functional.so | tee -a /home/vagrant/.phpenv/versions/*/etc/php.ini ; fi"

script:
  - phpunit --debug

notifications:
  email:
    - lstrojny@php.net
