language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make && make install; fi"

script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then echo extension=functional.so | tee -a /home/vagrant/.phpenv/versions/*/lib/php.ini ; fi"
  - sh -c "php --info"
  - phpunit

notifications:
  email:
    - lstrojny@php.net
