language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then php --info | grep ini ; done"
  - phpunit

notifications:
  email:
    - lstrojny@php.net
