language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -c "if [ -f .libs/functional.so ]; then php -n -d extension=.libs/functional.so /home/vagrant/.phpenv/shims/phpunit || exit 1; else ls -lh /home/vagrant/.phpenv/shims/phpunit || exit 1; fi"

notifications:
  email:
    - lstrojny@php.net
