language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -x ./ci.sh && echo "Success" || echo "FAILURE"; exit 1

notifications:
  email:
    - lstrojny@php.net
