language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"

script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then for f in /home/vagrant/.phpfarm/inst/php*/lib/php.ini ; do echo extension=functional.so > $f ; done ; php --re functional ; fi"
  - phpunit

notifications:
  email:
    - lstrojny@php.net
