language: php
php:
  - 5.3
  - 5.4

env:
  - FUNCTIONAL=native
  - FUNCTIONAL=userland PHPUNIT=phpunit

before_script:
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then phpize && ./configure && make; fi"
  - sh -c "if [ '$FUNCTIONAL' = 'native' ]; then PHPUNIT='php -n -dextension=.libs/functional.so `which phpunit`'; fi"

script:
  - sh -c "$PHPUNIT"

notifications:
  email:
    - lstrojny@php.net
